### ISSUE TITLE
Incompatibility with VanilaFix (outdated mixin)

### ISSUE THREAD

**Issue by SylveonBottle** [zeroeightysix/KAMI#187]
### Describe the bug
Game crashes with 1.12.2 VanillaFix 1.0.10-150.
The description of the mod claims that an outdated mixin could be the cause, since they updated to Mixins 8 with this version. However, when I downgraded to VanillaFix 1.0.10-99, the issue persisted. 
The game launches with only VanillaFix (KAMI Blue removed), and launches with only KAMI Blu (VanillaFix removed), but crashes when both are installed.

Crash log: https://paste.ee/p/pDoZF

### To Reproduce
1. Download and install KAMI Blue on a forge instance
2. Download and install [VanillaFix](https://www.curseforge.com/minecraft/mc-mods/vanillafix/files/) 
3. Launch game

### Additional context
Windows 10 Home v1909
Minecraft Launcher Runtime (jre-x64 version 1.8.0_51-b16)
Minecraft v1.12.2
Forge v14.23.5.2847
KAMI Blue v1.1.2+-58c5824
Vanilla Fix v1.0.10-150, v1.0.10-99

**Comment by dominikaaaa** [comment]
KAMI Blue specifically uses 0.7.8 Mixins due to Future compatibility, as shown by the comment on [line 65](https://github.com/kami-blue/client/blob/master/build.gradle#L65) in my `build.gradle`. The issue you're experiencing here is that it uses too new Mixins to work with KAMI Blue.

I opened this issue in their repo to try to get some help, no response: https://github.com/DimensionalDevelopment/VanillaFix/issues/226

I created this issue in my repo to keep track of it: https://github.com/kami-blue/client/issues/404 (closed as wontfix due to no reply)

Also, just a heads up this is the KAMI repo, the KAMI Blue repo is [kami-blue/client](https://github.com/kami-blue/client/)

**Comment by golfermatt** [comment]
It's kind of a hacky workaround but you can remove the code where kami redirects minecraft's crash reporter to make it work with vanillafix 1.0.10-99. The only caveat being that kami then cant save its config when minecraft crashes.

**Comment by dominikaaaa** [comment]
I don't think KAMI can save it's config when it crashes in the first place?

**Comment by golfermatt** [comment]
Unless i'm being an absolute knob, lines 98-101 in MixinMinecraft should save the config if minecraft crashes.


![Annotation 2020-04-09 130119 - Copy](https://user-images.githubusercontent.com/34506993/78936113-ca70df80-7a62-11ea-819f-2b8980da8db9.png)

**Comment by dominikaaaa** [comment]
I believe that's only if Minecraft has a safe exit, I've never had the config properly save with a crash.

**Comment by golfermatt** [comment]
Isn't the safe exit config save code in the next couple of lines that inject into the shutdown method?

**Comment by dominikaaaa** [comment]
Yes, and shutdown only runs when Minecraft is safely closed ie doesn't crash.

**Comment by golfermatt** [comment]
Wait, so then what does the redirect of displayCrashReport do?

**Comment by dominikaaaa** [comment]
Ah, I missed that. I guess it theoretically should save but I've never had it work with vanilla KAMI.

**Comment by zeroeightysix** [comment]
Please report kami blue issues on the [kami blue repository](https://github.com/kami-blue/client), instead of on the original KAMI repo.

If the error also happens on this version of KAMI, feel free to re-open.

**Comment by dominikaaaa** [comment]
086, it does happen with the original KAMI
