### ISSUE TITLE
java.lang.ClassNotFoundException: me.zero.alpine.EventBus

### ISSUE THREAD

**Issue by 22s** [zeroeightysix/KAMI#192]
when running latest builds of kami 1.14.4 it crashes and says its caused by: java.lang.ClassNotFoundException: me.zero.alpine.EventBus

**Comment by dominikaaaa** [comment]
That means your built jar doesn't include alpine. Are you sure you setup your workspace and used the proper jar? 
I don't think this is a KAMI specific issue

**Comment by 22s** [comment]
i'm just following the windows instructions w/ latest release. i download it and then run "gradlew.bat build" ive tried multiple releases

**Comment by dominikaaaa** [comment]
Which one *exactly* did you try and for sure got this error on?

**Comment by 22s** [comment]
https://github.com/zeroeightysix/KAMI/tree/d6f83356b464ea294e2a780f91357ebdd68f276f

KAMI-fabric-1.14-1.14.4-r1

**Comment by dominikaaaa** [comment]
Bruh moment. Idk, it just works for me. Try a dev env?

**Comment by 22s** [comment]
send jar im special :(

**Comment by dominikaaaa** [comment]
Uhhhh I can't do that, the jar is cached and my gradle cache has 20GB+ of shit, you have to do that yourself.

**Comment by 22s** [comment]
but i cant get it to work right bruuh

**Comment by dominikaaaa** [comment]
Instructions I wrote:
![dominikaaaa org-2020-07-08-20-12-43](https://user-images.githubusercontent.com/17222512/86982498-66d87a00-c157-11ea-965d-9f6f680e2314.png)

**Comment by 22s** [comment]
i have been trying for 1 hour now and im suffering :(

**Comment by dominikaaaa** [comment]
![](https://cdn.discordapp.com/attachments/672537344682754086/730594373754159114/Screenshot_20200708-212026.png)
I love having personal insults directed at me after trying to help and explaining the same thing 5 times 5 different ways, and sending 3 different pieces of documentation **which work for everybody else**.

**Comment by 22s** [comment]
yeah you didnt help at all, you tried to take this ticket upon yourself and can only repeat "read the instructions" and be condescending as fuck. answer tickets if you know how to solve the problem.

**Comment by dominikaaaa** [comment]
this isn't a "ticket", and I offered a solution. 

I did not take it upon myself, you messaged me first on discord, I just tried helping. 

If you call linking 3 different pieces of documentation, explaining the issue and giving you the solution, being insulted because I contributed to KAMI "being condescending" then I have no idea what I'm supposed to tell you.

**Comment by zeroeightysix** [comment]
The fabric branch is not ready for release and does not yet have its `build.gradle` set up for building real, runnable artifacts. As far as I know, the problem is that no dependencies are included in the built jar.

I'll happily accept a PR that fixes this - look into loom's `include` task.

For the time being, KAMI for 1.14.4 only works in a development environment. Make sure you correctly import the project, by selecting the `build.gradle` file when importing.

**Comment by 22s** [comment]
will there ever be a stable release?

**Comment by zeroeightysix** [comment]
@22s Yes. Up until the 8th I have been working to get a release ready. I will begin working again around the 24th and I hope to get a release out next month.

**Comment by zeroeightysix** [comment]
Builds work now.
