### ISSUE TITLE
Crash on startup with latest commit

### ISSUE THREAD

**Issue by NepNep21** [zeroeightysix/KAMI#541]
**Describe the bug**
Crash on startup 

**To Reproduce**
1. Download the latest commit to fabric from actions (a63151316daa7e31223222a3903109c03d374c4d)
2. Attempt to start up the game
3. Experience crash

**Expected behavior**
The game loading without crashing

**Screenshots**

**Environment**
Did you build KAMI yourself? If so, on what commit? If not, which release did you download?
Commit a63151316daa7e31223222a3903109c03d374c4d directly from github actions

What operating operating system?
Linux 5.3.18 (openSUSE leap 15.2)

What version of java?
java 8u282-b08

**Additional context**
Crash report: https://pastebin.com/ZVRneET1
It contains other mods but i have confirmed that it also doesn't work without them

**Comment by nopjmp** [comment]
What was the last version of KAMI you were using? we didn't update the libraries between feb and march. it crashes on start now because we are actually initializing the GUI at the start instead of before where it was doing it late. The crash you are getting is it's failing to find a compatible libm.so file but it should be compatible with openSUSE Leap unless something broke / changed in openSUSE.

**Comment by Lolicon2110** [comment]
Not sure honestly, i just know it was somewhere in february or january (probably february) (I used windows 10 then)

**Comment by B2H990** [comment]
This issue occurs with most stable distros as they bundle older versions of GLIBC see if you can backport it from newer releases of opensuse (No Idea how to do that on opensuse as I run debian and they make it quite easy)

**Comment by billy4479** [comment]
I had the same issue. Then I tried disabling all my other mods one by one and it turned out that it was because of malilib and/or other masa's mods. With those out of the way I am able to play normally.

<details>
<summary>Specs</summary>
OS: Arch Linux (kernel version 5.11.6)

Java: openjdk 11.0.10
Built myself on a63151316daa7e31223222a3903109c03d374c4d
Logs: [https://pastebin.com/LuFUZ9ub](https://pastebin.com/LuFUZ9ub)
</details>

**Comment by LordMZTE** [comment]
> I had the same issue. Then I tried disabling all my other mods one by one and it turned out that it was because of malilib and/or other masa's mods. With those out of the way I am able to play normally.
> Specs
> OS: Arch Linux (kernel version 5.11.6)

Seems to be a mixin conflict with tweakeroo.

**Comment by billy4479** [comment]
> Seems to be a mixin conflict with tweakeroo.
> This is very likely a seperate issue
Oh, sorry, my bad. Should I open a new issue here or in Tweakeroo's repo?

**Comment by LordMZTE** [comment]
> > Seems to be a mixin conflict with tweakeroo.
> > This is very likely a seperate issue
> 
> Oh, sorry, my bad. Should I open a new issue here or in Tweakeroo's repo?

Well, this may not even be a problem with KAMI and tweakeroo, but it could be any other mod and tweakeroo. But i guess they are using a `@Redirect` mixin, which is pretty much always a problem, because that way you can never have 2 mixins on the same function. But this isn't directly anyone's fault. If youre gonna report this, then probably to tweakeroo, just for the "Dangerous" kind of mixin they're using.

**Comment by l1ving** [comment]
> because that way you can never have 2 mixins on the same function.

You can, just not a redirect

**Comment by LordMZTE** [comment]
> > because that way you can never have 2 mixins on the same function.
> 
> You can, just not a redirect

yes, as i stated

**Comment by ForBai** [comment]
Same problem.
I a m also using Linux Ubuntu

**Comment by ForBai** [comment]
You could solve it when you disable splashscreen idk how

**Comment by brandonplank** [comment]
I believe this is caused by Optifabric, When mine was crashing, it said it was because of a conflict with it and this package.

**Comment by Lolicon2110** [comment]
> I believe this is caused by Optifabric, When mine was crashing, it said it was because of a conflict with it and this package.

I wasn't using optifabric
