### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by DagggotMc** [zeroeightysix/KAMI#549]
Im on a mac i downloaded the latest verstion of fabric and kami and i crash as soon as the new app opens up and it says

The game crashed whilst initializing game
Error: java.lang.UnsatisfiedLinkError: /private/var/folders/pl/nyrd9d5558l872xz73d6ks2c0000gp/T/imgui-java-natives_1621264659643/libimgui-java64.dylib: dlopen(/private/var/folders/pl/nyrd9d5558l872xz73d6ks2c0000gp/T/imgui-java-natives_1621264659643/libimgui-java64.dylib, 1): Library not loaded: /usr/local/opt/freetype/lib/libfreetype.6.dylib
Exit Code: 255

get a mac download kami and fabric run fabric and then u get crash

i expectied it to work lol

i am on mac
downloaded from github marched edition

i did not put -noverify in jvm arguments and it didn't even work when it was the only mod in mods folder

**Comment by LordMZTE** [comment]
This is happening because imgui native libraries are only included for linux and windows, not for mac. Not sure if anyone is gonna fix this, as supporting mac is always a nightmare. And quite honestly, I don't think it's worth supporting either. Honestly, just get yourself a proper operating system :D

**Comment by zeroeightysix** [comment]
If you have brew, `brew install freetype`.

[brewinstall.org](https://brewinstall.org/install-freetype-on-mac-with-brew/)
